name: Provision Infrastructure

on: 
  workflow_dispatch:

jobs:

  plan-infrastructure-staging:
    name: Plan Staging Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Infra
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform Init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform init -backend-config="key=darojo/stg/terraform.tfstate"  -reconfigure

      - name: Terraform Plan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform plan -var-file="./Env/stg.tfvars" -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -out=tfplan-staging.binary

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-staging
          path: ./Infra/tfplan-staging.binary
          retention-days: 5

  manual-approval-staging:
    name: Review Staging Plan
    runs-on: ubuntu-latest
    needs: plan-infrastructure-staging
    if: success()
    environment: Manual-Approval  
    steps:
      - name: Await approval
        run: echo "Approval granted, proceeding to apply"

  provision-infrastructure-staging:
    name: Provision Staging Infrastructure
    runs-on: ubuntu-latest
    needs: manual-approval-staging
    if: success()
    defaults:
      run:
        working-directory: ./Infra
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform Init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform init -backend-config="key=darojo/stg/terraform.tfstate"  -reconfigure

      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan-staging
          path: ./Infra

      - name: Apply Staging
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform apply -auto-approve tfplan-staging.binary

  manual-approval-plan-prod:
    name: Manual Approval
    runs-on: ubuntu-latest
    needs: provision-infrastructure-staging
    if: success()
    environment: Manual-Approval  
    steps:
      - name: Await approval
        run: echo "Approval granted, proceeding to apply"

  plan-infrastructure-prod:
    name: Provision Prod Infrastructure
    runs-on: ubuntu-latest
    needs: manual-approval-plan-prod
    if: success()
    defaults:
      run:
        working-directory: ./Infra
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform Init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform init -backend-config="key=darojo/prod/terraform.tfstate"  -reconfigure

      - name: Terraform Plan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform plan -var-file="./Env/prod.tfvars" -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -out=tfplan-prod.binary

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-staging
          path: ./Infra/tfplan-prod.binary
          retention-days: 5

  manual-approval-prod:
    name: Manual Approval
    runs-on: ubuntu-latest
    needs: plan-infrastructure-prod
    if: success()
    environment: Manual-Approval  
    steps:
      - name: Await approval
        run: echo "Approval granted, proceeding to apply"

  provision-infrastructure-prod:
    name: Provision Prod Infrastructure
    runs-on: ubuntu-latest
    needs: manual-approval-plan-prod
    if: success()
    defaults:
      run:
        working-directory: ./Infra
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan-prod
          path: ./Infra

      - name: Terraform Init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform init -backend-config="key=darojo/prod/terraform.tfstate"  -reconfigure

      - name: Terraform Apply
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform apply -auto-approve tfplan-prod.binary