name: Provision Infrastructure

on: 
  workflow_dispatch:

jobs:

  Plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: CD into Infra
        run: cd Infra

      - name: init
        run: terraform init -backend-config="key=darojo/stg/terraform.stg"  -reconfigure

      - name: pwd
        run: pwd

      - name: ls -l 
        run: ls -l

      - name: plan
        run: terraform plan -var-file="Infra/Env/stg.tfvars" -out=tfplan.binary

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan.binary
          retention-days: 5

  manual-approval:
    name: Manual Approval
    runs-on: ubuntu-latest
    needs: Plan
    if: success()  
    steps:
      - name: Await approval
        run: echo "Approval granted, proceeding to apply"

  provision_infrastructure:
    name: Provision staging infrastructure
    runs-on: ubuntu-latest
    needs: manual-approval
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: init
        run: terraform init -backend-config="key=darojo/stg/terraform.stg"  -reconfigure

      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan

      - name: apply
        env:
          SUBSCRIPTION_ID: ${{ secrets.subscriptionId }}
        run: terraform apply -var="subscription_id=${{ env.SUBSCRIPTION_ID }}" -auto-approve


